version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: liuboicliucizdesivsempoh
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: 3306
            user: root
            password: $mypass
            migrations: true
  mysql-db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: $mypass
      MYSQL_ROOT_PASSWORD: $myrootpass
      MYSQL_DATABASE: $mydatabase
    volumes: 
      - mysql:/var/lib/mysql
    
volumes:
  mysql: ~
